server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: streamly-backend

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:${DB_PORT:5432}/streamly_db}
    username: ${SPRING_DATASOURCE_USERNAME:streamly_admin}
    password: ${SPRING_DATASOURCE_PASSWORD:streamly_password}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG
